### ISSUE TITLE
cannot import autopacmen-Paulocracy

### ISSUE THREAD

**Issue by tutentaten** [ARB-Lab/autopacmen#2]
Hi!

After successfully installing autopacmen-Paulocracy using pip I cannot import the package.
 
import autopacmen-Paulocracy

produces a syntax error due to the hyphen. Attempting to import the package otherwise such as

impo = __import__("autopacemn-Paulocracy")

produces a ModuleNotFoundError.

How does one access the module after a pip install?

**Comment by Paulocracy** [comment]
Hello \o/ and sorry for the very late reply!

As you've probably found out already, autopacmen can be imported using
`import autopacmen`
The "-Paulocracy" suffix is only relevant for the pip installation process.
