### ISSUE TITLE
error running ec_model_2019_06_25_sMOMENT_iJO_CREATION.py

### ISSUE THREAD

**Issue by tutentaten** [ARB-Lab/autopacmen#3]
Hi!

After downloading the 'brenda_download.txt' and saving it in the '/ecModel_2019_06_25_input'-folder and running ec_model_2019_06_25_sMOMENT_iJO_CREATION.py, I get the following error message.

```
Traceback (most recent call last):
  File "C:/Users/cga32/OneDrive/autopacmen-master/autopacmen/ec_model_2019_06_25_sMOMENT_iJO_CREATION.py", line 46, in <module>
    parse_brenda_textfile(brenda_textfile_path, bigg_metabolites_json_folder, json_output_path)
  File "C:\Users\cga32\OneDrive\autopacmen-master\autopacmen\submodules\parse_brenda_textfile.py", line 84, in parse_brenda_textfile
    lines = f.readlines()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 4133: character maps to <undefined>
```

I figured I could fix this by adding "encoding='utf-8' in the open function in parse_brenda_textfile.py at line 83.
However, doing this leads to another error:

```
Traceback (most recent call last):
  File "C:/Users/cga32/OneDrive/autopacmen-master/autopacmen/ec_model_2019_06_25_sMOMENT_iJO_CREATION.py", line 46, in <module>
    parse_brenda_textfile(brenda_textfile_path, bigg_metabolites_json_folder, json_output_path)
  File "C:\Users\cga32\OneDrive\autopacmen-master\autopacmen\submodules\parse_brenda_textfile.py", line 147, in parse_brenda_textfile
    ec_number.lower().split("(transferred to ec")[1].replace(")", "").lstrip()
IndexError: list index out of range

```
The script should run smoothly, so would anyone have any idea what is going wrong here? Maybe the encoding should be something else than utf-8, but from what I've understood the brenda_download.txt file is in utf-8 format.

**Comment by Paulocracy** [comment]
Hello and thank you for the issue :D

I looked into your problems and found out that the newest BRENDA text file version has some inconsistent lines that did not exist in the older text file that I used for testing AutoPACMEN. Thus, I'm releasing a new version (0.5.5) which hopefully fixes your issue.

In addition, this version also fixes also two other bugs: One that occurred in the generation script for iJO1366*, specifically in the generation of the protein data spreadsheet, and one happens if an organism has a "/" inside its name which is the case in the newest BRENDA text file as it is parsed by AutoPACMEN.

**Comment by tutentaten** [comment]
Great! It now works perfectly. Still has to add the "encoding='utf-8' but that might differ from computer to computer as far as I have understood.

Thank you very much!:)

**Comment by Paulocracy** [comment]
Gladly :-)
I could not reproduce the encoding error indeed, I'll change the encoding for the next release. And another hopefully working alternative workaround should be to change the BRENDA text file's encoding.

**Comment by tutentaten** [comment]
Great!:)
