### ISSUE TITLE
Error in data_parse_brenda_textfile.py

### ISSUE THREAD

**Issue by yaccos** [ARB-Lab/autopacmen#5]
In line 45 of `data_parse_brenda_textfile.py`, there is a bug where the click options `type=click.Path(exists=True, dir_okay=True)` force the output file to exist even though the purpose of the function is to create it. Hence, trying to run the command results in the error: `type=click.Path(file_okay=True, dir_okay=True, writable=True)`. I suggest changing these options to `type=click.Path(file_okay=True, dir_okay=True, writable=True)` as in `data_parse_brenda_json_for_model.py`.

**Comment by Paulocracy** [comment]
I agree with you and changed the line accordingly.
