### ISSUE TITLE
Add default argument to get_reactions_kcat_mapping

### ISSUE THREAD

**Issue by yaccos** [ARB-Lab/autopacmen#7]
When using `get_reactions_kcat_mapping`, you may not have any user-defined protein database. Hence, requiring the argument `protein_kcat_database_path` to have a value is therefore counterintuitive. From inspecting the function, I find that supplying an empty string as the value will make the function ignore the database. I therefore suggest having the empty string as the default argument for  `protein_kcat_database_path`.

**Comment by Paulocracy** [comment]
I (once again :-) agree with you and added a default parameter.
